---
version: "3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - ${homepage_config_dir}:/app/config
    ports:
      - 3000:3000
    restart: unless-stopped
