---
version: "3"

volumes:
  postgres:
    driver: local

services:
  guacamole:
    image: jwetzell/guacamole:arm32v7
    container_name: guacamole
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - postgres:/config
    ports:
      - 50545:8080
    restart: unless-stopped
