version: '3.3'

volumes:
  speedtest_data:

services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker:latest-arm
    container_name: speedtest
    environment:
      - TZ=Europe/Brussels
      - PGID=1000
      - PUID=1000
      - OOKLA_EULA_GDPR=true
    ports:
      - 8090:80
    volumes:
      - speedtest_data:/config
    restart: unless-stopped

