version: '3'

networks:
  traefik:
    driver: bridge
    name: traefik
 
services:
  reverse-proxy:
    image: traefik:v2.9
    container_name: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8085:8080
    networks:
      - traefik
