---
version: "3.3"

volumes:
  homepage_config:

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 8095:3000
    volumes:
      - homepage_config:/app/config