---
version: "3.3"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - ~/.docker/homepage:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.local`)"
      - "traefik.http.routers.whoami.entrypoints=http"
