---
- Management:
    - Proxmox:
        icon: proxmox.png
        href: $URL
        description: Hypervisor
    - Gitea:
        icon: gitea.png
        description: Git repos
        href: $URL
        server: my-docker
        container: gitea
    - AdGuard: 
        icon: adguard-home.png
        href: $URL
        description: DNS filtering
        server: my-docker
        container: adguardhome

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: $URL
        description: Media center
        server: my-docker
        container: jellyfin
        widget:
          type: jellyfin
          url: $URL
          key: $KEY
    - Jellyseerr:
        icon: jellyseerr.png
        href: $URL
        description: Request media
        server: my-docker
        container: jellyseerr
        widget:
          type: jellyseerr
          url: $URL
          key: $KEY
    - qBittorrent:
        icon: qbittorrent.png
        href: $URL
        description: Torrent downloader
        server: my-docker
        container: qbittorrent
        widget:
          type: qbittorrent
          url: $URL
          username: $USER
          password: $PASS
    - Sonarr:
        icon: sonarr.png
        href: $URL
        description: TV shows
        server: my-docker
        container: sonarr
        widget:
          type: sonarr
          url: $URL
          key: $KEY
    - Radarr:
        icon: radarr.png
        href: $URL
        description: Movies
        server: my-docker
        container: radarr
        widget:
          type: radarr
          url: $URL
          key: $KEY
    - Bazarr:
        icon: bazarr.png
        href: $URL
        description: Subtitles
        server: my-docker
        container: bazarr
        widget:
          type: bazarr
          url: $URL
          key: $KEY

- Network:
    - Wireguard:
        icon: wireguard.png
        description: VPN
        server: my-docker
        container: wireguard
    - Speedtest:
        icon: speedtest-tracker.png
        href: $URL
        description: Internet speed
        server: my-docker
        container: speedtest
        widget:
          type: speedtest
          url: $URL

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: $URL
        description: Metrics dashboards
    - Prometheus:
        icon: prometheus.png
        href: $URL
        description: Metrics
        widget:
          type: prometheus
          url: $URL

- Extra:
    - Prowlarr:
        icon: prowlarr.png
        href: $URL
        description: Indexer
        server: my-docker
        container: prowlarr
        widget:
          type: prowlarr
          url: $URL
          key: $KEY
    - TwitchMiner:
        icon: twitch.png
        description: Twitch point miner
        server: my-docker
        container: twitchminer
