version: '3.6'

networks:
  traefik:
    driver: bridge
    name: traefik

volumes:
  gitlab_config:

  gtlab_logs:

  gitlab_data:

services:
  web:
    image: 'gitlab/gitlab-ce:15.6.7-ce.0'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.example.com'
    ports:
      - 8082:80
      - 443:443
      - 2222:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git.rule=Host(`git.local`)"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
