---
version: "3"
volumes:
  speedtest_data:

services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker:latest
    container_name: speedtest
    environment:
      - TZ=Europe/Brussels
      - PGID=${speedtest_PUID}
      - PUID=${speedtest_PUID}
      - OOKLA_EULA_GDPR=true
    ports:
      - 8090:80
    volumes:
      - speedtest_data:/config
    restart: unless-stopped
