---
version: "3"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:0.99-porterdavid
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8050:8080
    restart: unless-stopped