---
version: "3"
volumes:
  adguardhome_data:
  adguardhome_config:

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 8080:80/tcp
      - 44301:443/tcp
    volumes:
      - adguardhome_data:/opt/adguardhome/work
      - adguardhome_config:/opt/adguardhome/conf
    restart: unless-stopped
