---
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8020:8080
    command: "--interval 86400 --cleanup --http-api-metrics --http-api-token $TOKEN"
    restart: unless-stopped
