---
version: "3"
volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy
    container_name: caddy
    volumes:
      - ${location_caddyfile}:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
