---
version: "3.8"

volumes:
  wireguard_data:

services:
  wg-easy:
    environment:
      - WG_HOST=$HOST
      - WG_PORT=51820
      - WG_ALLOWED_IPS=$RANGE1,$RANGE2
      - WG_DEFAULT_DNS=$DNS1,$DNS2
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - wireguard_data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1